# -*- coding: utf-8 -*-
"""analyze_sequencing_data_for_cancer_mutation_detection.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLgScgfIHy_w9ihff2yWYZ3mSHtPGiN2
"""

#import necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#read in data from csv file 
data = pd.read_csv('epigenetic_modifications.csv') 
#check data types and shape of the dataframe 
print(data.info()) 
print(data.shape) 

 #separate the features and labels 
X = data.iloc[:,:-1]  #features 
y = data['label'] #labels  

 #scale the features using StandardScaler 
scaler = StandardScaler()  #instantiate scaler object  
X = scaler.fit_transform(X) #fit and transform the features  

 #split the dataset into training and testing sets  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  

 #build a logistic regression model to analyze epigenetic modifications in cancer cells for drug development and precision medicine applications  
logreg = LogisticRegression()    #instantiate logistic regression object  
logreg.fit(X_train, y_train)     #fit the model on training set   

 #make predictions on test set   
y_pred = logreg.predict(X_test)   

 #evaluate model performance   
accuracy = accuracy_score(y_test, y_pred)     #calculate accuracy score    print('Accuracy: %f' % accuracy)    

confusionMatrix = confusionMatrix(yTest, yPred)     
print('Confusion Matrix: \n', confusionMatrix)    

classificationReport = classificationReport(yTest, yPred)     
print('Classification Report: \n', classificationReport)